# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'Goof'
    testType: 'app'
    severityThreshold: 'critical'
    monitorWhen: 'always'
    failOnIssues: false

- script: |
    docker build -t goof
    docker images 
    docker images | grep goof
    sudo docker images | grep goof
  displayName: 'build Docker image'

- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'Goof'
    testType: 'container'
    dockerImageName: 'goof'
    dockerfilePath: 'Dockerfile'
    monitorWhen: 'always'
    failOnIssues: true