# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-2019

steps:
- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'Goof'
    testType: 'app'
    severityThreshold: 'critical'
    monitorWhen: 'always'
    failOnIssues: false

- script: |
    docker build -t goof .
    docker images 
    docker images | grep goof
    sudo docker images | grep goof
  displayName: 'build Docker image'

- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'Goof'
    testType: 'container'
    dockerImageName: 'goof'
    dockerfilePath: 'Dockerfile'
    monitorWhen: 'always'
    failOnIssues: false
    additionalArguments: 
    organization: 
    projectName: 
    severityThreshold
  
  - script: |
      node -v 
      npm -v
      npm install -g snyk
      snyk -v
      dir
      snyk auth '479e7f58-33d3-470c-a13e-d258edb10092'
      snyk code test
'
