# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-2019

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
 #snyk code 
  - script: |
      node - v
      npm - v
      npm install - g snyk
      snyk -v 
      dir 
      snyk auth ' bd0a621f-e440-4b09-8791-dd261466fcd0'
      snyk code test
    continueOnError: true
    displayName: 'snyk code' 
  


